### ISSUE TITLE
New Branch

### ISSUE THREAD

**Issue by midnightwolflp** [scorpneo/HelloWorld#8]
Despite being on a computer, I am not able to make my own branch from HelloWorld. Can someone look into this?

**Comment by Vishruth094** [comment]
You have to click on master branch, search up the branch you want to make and the computer will say make branch...

**Comment by Vishruth094** [comment]
Also look at the guide

**Comment by midnightwolflp** [comment]
I know that, but it won’t let me create a new branch in the drop down box

**Comment by midnightwolflp** [comment]
I had to fork the repo to make mine

**Comment by midnightwolflp** [comment]
You made one?

**Comment by Vishruth094** [comment]
Actually nvm it let me fork but not create a branch
